
---
- hosts: all
  become: true
  vars:
    ansible_become_pass: yoav
  tasks:
  -  name: install nginx
     ansible.builtin.package: pkg=nginx state=latest
     notify: start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started
