---
# Download containerd
# Install as systemd service
# Download and Install runc
# Downlaod and install cni plugins

- name: Download containerd
  ansible.builtin.get_url:
      url: https://github.com/containerd/containerd/releases/download/v{{ version }}/containerd-{{ version }}-linux-amd64.tar.gz
      dest: /tmp/containerd.tar.gz

- name: Install containerd
  become: true
  ansible.builtin.unarchive:
      src: /tmp/containerd.tar.gz
      dest: /usr/local

- name: Download unit file for containerd
  become: true
  ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
      dest: /etc/systemd/system/containerd.service

- name: Enable containerd service
  ansible.builtin.systemd:
    daemon_reload: yes
    
