---
# Download containerd
# Install as systemd service
# Download and Install runc
# Downlaod and install cni plugins

- name: Install containerd
  become: true
  ansible.builtin.unarchive:
      src: https://github.com/containerd/containerd/releases/download/v{{ nerd_version }}/containerd-{{ nerd_version }}-linux-amd64.tar.gz
      remote_src: true
      dest: /usr/local

- name: Download unit file for containerd
  become: true
  ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
      dest: /etc/systemd/system/containerd.service

- name: Enable containerd service
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
    name: containerd
    enabled: true

- name: Install runc
  become: true
  ansible.builtin.get_url:
      url: https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64  
      mode: '+x'
      dest: /usr/local/sbin/runc

- name: Create CNI directory
  become: true
  ansible.builtin.file:
      state: directory
      path: /opt/cni/bin

- name: Install CNI plugins
  become: true
  ansible.builtin.unarchive:
      src: https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/cni-plugins-linux-amd64-v{{ cni_version }}.tgz
      remote_src: true
      dest: /opt/cni/bin

